### PR TITLE
Remove prometheus from docker image

### PR DESCRIPTION
**Pull request by NuwanSameera**
Rabbitmq now includes a version of that plugin by default

### CODE REVIEW

**Comment by NuwanSameera** [comment]
My issue solved after doing this changes.

Thank you.

**Comment by ViliusS** [comment]
My question was to Google :)

@NuwanSameera maybe you can rebase your work on the latest changes in master branch?

**Comment by armandomiani** [comment]
will be merged via https://github.com/GoogleCloudPlatform/rabbitmq-docker/pull/79#pullrequestreview-947180219 due CLA

**Comment by NuwanSameera** [comment]
Is this PR closed without Merged due to CLA issue ?

**Pull request closed without merging**
