### PR TITLE
Updated versions

### PR DESCRIPTION
**Pull request by ovk6**

### CODE REVIEW

**Comment by wgrzelak** [comment]
@ovk6 please fix the build

**Comment by wgrzelak** [comment]
@ovk6 Olga, could you take an action regarding to this PR? Please close it, or fix the build.

**Comment by ovk6** [comment]
@wgrzelak There is an open issue for that: b/132948068

**Comment by wgrzelak** [comment]
@ovk6 can the PR be closed?

**Comment by ovk6** [comment]
Outdated

**Pull request closed without merging**
